### ISSUE TITLE
Drag forward/backward in defn arg list should change calling sites as well

### ISSUE THREAD

**Issue by NoahTheDuke** [clojure-lsp/clojure-lsp#1131]
**Is your feature request related to a problem? Please describe.**
When editing a function definition, it's cumbersome to rearrange the order of the arguments, as this requires finding all places where it's called and editing them similarly as well.

**Describe the solution you'd like**
Expand the code actions "Drag forward" and "Drag backward" to apply their changes to all calling sites as well.

**Describe alternatives you've considered**
Instead of using Drag forward/backward, you could create whole new code actions.

**Additional context**
Things to think about: What if the call site is in a threading macro? What if the function is used in an `apply` or `partial`?

**Comment by ericdallo** [comment]
Not sure if we should use the existing drag code actions, not sure would be clear to user what the code action would do, maybe we should have different code actions specific for that.
WDYT @mainej ?

**Comment by mainej** [comment]
I agree, this would be a nice feature. We could certainly use some of the `drag` code to implement it. It handles threading, though maybe not `partial` or `apply`. I'm not sure whether it'd be better as an extension to drag, or as its own code action. If we added it to drag, it'd be nice if we asked "It looks like you're editing a method signature. Would you like to change call sites too? #clippy" so that you could opt out. We'd also have to decide whether it would activate only at var-definitions, or also at var-usages.

As far as prior art goes, there's a lot more you could do. The fanciest tool I ever used was IntelliJ's [change signature](https://www.jetbrains.com/help/idea/change-signature.html). It didn't always work, but when it did, it was amazing. Not only could you reorder arguments, you could also add and remove them. When adding an argument there were all sorts of options. You could introduce another arity for the definition to supply a default, or add a default value to all the call sites, or even inspect the call sites to see if they had a local in scope with the right type that could be supplied as a new param. I'm not suggesting we do any of that now, but ... maybe someday.

**Comment by NoahTheDuke** [comment]
> I'm not sure whether it'd be better as an extension to drag, or as its own code action. If we added it to drag, it'd be nice if we asked "It looks like you're editing a method signature. Would you like to change call sites too? #clippy" so that you could opt out. We'd also have to decide whether it would activate only at var-definitions, or also at var-usages.

This makes me think it should be a separate pair of actions. It's nice when you can bind a code action to a key combo and then just hit it without additional input.

**Comment by mainej** [comment]
I'm working on this and realized `partial` causes problems.

```clojure
(defn f [a b c])

(partial f :a :b)
```

Suppose you want to drag `b` forward. That makes `c` the second parameter, but at the call site we don't have a corresponding argument: `(partial f :a ???)`.

@ericdallo or @NoahTheDuke do you have thoughts about what to do in this case? With the code I have at the moment, the call site ends up untouched: `(partial f :a :b)`. Is that acceptable?

**Comment by mainej** [comment]
> `partial` causes problems

To address this case, I decided to ask the user a Yes/No question "Not all call sites can be updated. Continue anyway?"

If they answer Yes, then the defn and as many call sites as possible are edited. That is, we get `(defn f [a c b])` but no changes at `(partial f :a :b)`.

If they answer No, then nothing is edited.

@ericdallo and @NoahTheDuke does that sound OK? Do you have opinions about the phrasing of the question? It could also be:

```
Not all call sites can be updated.
---------
> Edit as many call sites as possible.
  Do not apply edits.
```

Or this would also be easy to implement:

```
Not all call sites can be updated.
---------
> Edit definition and as many call sites as possible.
  Edit definition only.
  Do not apply edits.
```

**Comment by snoe** [comment]
If you don't know which call sites can't be updated, the option to continue anyways is introducing bugs that would be hard to find and only be caught at runtime. So I think we should fix all sites if we can or nothing.

`partial` could convert to a literal fn, in the example convert to `(partial f :a :b)` > `#(f :a % :b)` but it makes me wonder about other partial-like macros, for instance thread calls `(->> c (f :a :b))`, let alone user macros, or functions that mess with arg order.

**Comment by snoe** [comment]
Other worries.

```clojure
(apply f args)

(defn exec [k a b c] 
  (let [fns {:x f :y g :z h}] 
    ((get fns k) a b c)))
```

**Comment by mainej** [comment]
> we should fix all sites if we can or nothing

That was my initial impulse @snoe  and it would be easy to change the code I have to implement that. But after thinking about it more, "do nothing" might not be ideal either. That is, if you have 25 call sites, 2 of which can't be updated, which is better?

- Change 23 of them automatically, suggesting to the user that they should review all the references carefully to find the other 2.
- Change 0 of them, forcing the user to find and perform all 25 refactorings perfectly.

Both are susceptible to the same problems—that the user won't review every call site or won't correctly perform the manual refactoring—but the second asks the user to review and edit way more sites. As the number of call sites goes up, the tedium of finding the next reference ("wait, did I skip one?") and performing the drag ("wait, was it forward or backward?") would make bugs _more_ likely, I would think.

It's a lose-lose situation, so I'm willing to go with whatever you all think, even if that means scrapping the feature entirely.

I'll double-check what happens currently with some of the other examples you mentioned @snoe (threading, `apply`, and function lookup). My guess is that those will be counted as "can't edit", but it'll be good to check. As it's written so far, the refactoring is only offered when on a param defined by `def`, `defn` or `defmacro`, so I'm not too worried about user macros. (It's also not offered on multi-arity functions. Perhaps it could be someday, but I didn't want to include that in the first draft.)

> partial could convert to a literal fn

When I was working on `promote-fn` I thought about promoting `partial` to `#()`, but that's tricky too. Let's take the example we've been looking at `(partial f :a :b)`. As you said, it could be promoted to `#(f :a :b %)` before having the args dragged. But that only works because we know that `f` is an arity-3 function. If it had multiple arities, that'd be hard to capture with `#()`. The best you can do is `#(apply f :a :b %&)`, which I believe is equivalent to the version that uses partial. But that form is so ugly that I've never seen it in real code. Usually it's possible to refactor to something cleaner, but only by leaning on external knowledge about what's passed to the `partial`ed function. I guess in theory we could try to assist with that refactoring, but it would probably be slower than just doing it manually.

Anyway, I'd rather not think about promoting `partial` yet, and instead consider it a location where we can't drag args, at least for the first draft of this. WDYT?

**Comment by mainej** [comment]
To confirm... threading, `apply` and function lookup are counted as "can't edit". But it was good to check. Function lookup was doing something weird. Thanks for the suggestions @snoe.

**Comment by NoahTheDuke** [comment]
Good analysis, @mainej. I lean towards fixing as much as possible and surfacing somehow the list of places where fixes couldn't be applied. I agree that promoting `partial` is a mistake.

**Comment by snoe** [comment]
It's been an important principle of this project to not leave user code in a broken state through partial refactors. 

So, if you look at the way intellij (java; possibly cursive too) handles these kind of cases: it presents the list of locations to the user that can't be automatically applied, so the user can step through each one, jumping to the location and commit/edit/reject them. The process is very similar to merge tools; in git if there's a merge conflict you see what couldn't be applied and have to either fix or abort the merge. You don't get a message like "200 of 204 files merged properly, it's up to you to find the ones that didn't".  I don't think LSP has the capability to "stage" edits and allow user intervention at all the locations? Maybe it does and I think that would be the approach to take here.


BUT if we take the All or None approach, I suspect that we would hit the All case in the vast majority of situations. Personally I see myself using this when I'm first making a call to `f` and realize that I want some arg moved for partial or threading, not so much on pre-existing and widely used functions. So that would be my recommendation, I think the feature is useful even if it can't always be applied.

My view on this lose-lose:
> Change 23 of them automatically, suggesting to the user that they should review all the references carefully to find the other 2.
> Change 0 of them, forcing the user to find and perform all 25 refactorings perfectly.

I'll argue the first case is worse, because you will be lulled into accepting, and miss one of the weird places. In the second case, you know you have to change each one AND you have no one to blame but yourself if you miss something. The thing that intellij adds is an "apply safe" button, that then narrows down the full list into those that require manual intervention and then a "do refactor" and "cancel" buttons when you are satisfied with your manual edits.

**Comment by ericdallo** [comment]
Yeah, I'm leaning to agree with @snoe, do or nothing with a clear message that we can't apply "check apply, threads etc"...
If we find a way to have a good UX like Idea and other IDEs custom features, we can improve this in the future IMO

**Comment by NoahTheDuke** [comment]
As you noted, @snoe, even "safe" changes could miss usages, such as `(resolve (symbol "my-fn"))`.

Given that, what if this was an LSP extension? Instead of relying on existing `codeAction` machinery, this would be a command like `serverInfo` that applies the change and returns a list of known locations that couldn't be safely changed. Then, it's on clients to properly implement displaying that list of locations. This means only confirming clients (or users who are bold) will be able to use this.

Could work like the "safe apply" button you mentioned in IntelliJ.

**Comment by snoe** [comment]
@NoahTheDuke Yeah, intellij has an option to "search strings and comments" for refactors and flag that. I could see us adding that flag for general refactorings. But that string could always come in from outside the program, so I'd put your example in the `eval` hole that we do fail at for pretty much all refactorings. That's pretty much the line we have to draw: if it's invisible to analysis, it's invisible to our refactorings.

I'm not sure an extension like you describe would be very portable, if each client (or worse user) has to implement handling this special case, we're back to pre-lsp days. I'd rather see a push for LSP to add the flow to their spec (some googling finds similar requests).

**Comment by NoahTheDuke** [comment]
> I'm not sure an extension like you describe would be very portable, if each client (or worse user) has to implement handling this special case, we're back to pre-lsp days. I'd rather see a push for LSP to add the flow to their spec (some googling finds similar requests).

You're absolutely right that it wouldn't be portable, which sucks. Bummer that we're stuck waiting on the LSP spec to support such a thing. I would be willing to write the code for vim/coc.nvim, but that would leave quite a few behind.

**Comment by mainej** [comment]
I'll abort the refactoring and show a warning. I wonder if the spec will ever support more interactive refactorings. Probably unlikely. I suppose you could navigate the user to each call site and ask them what to do. But that's sort of the [text-based adventure game](https://en.wikipedia.org/wiki/Colossal_Cave_Adventure) version of refactoring. Not as good as IntelliJ's GUI.

One thing we could do is abort _and_ navigate the user to the first call site that couldn't be refactored. That might be too jarring though. What do you all think?

**Comment by ericdallo** [comment]
I already saw features being added to LSP spec that started with a issue, I think we could try that opening a issue on the LSP spec itself, sounds like something pretty useful for lost of refactorings and other things that need a communication and a confirmation on client side.
We do have [window/showMessageRequest](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessageRequest) which is simple but allows server ask something to client and client respond with a pre-selected answer, I know this is simple, but maybe we could think on a first iteration of this feature
