### ISSUE TITLE
The SymbolProvider line info gets out of whack when editing the file in Calva

### ISSUE THREAD

**Issue by PEZ** [clojure-lsp/clojure-lsp#1178]
If I edit the file, adding/removing lines, then the Outline links to the wrong locations of the file.

This gets extra problematic with the new Sticky Scroll feature of VS Code, where the symbol provider is used to inform what should stick while scrolling. Here's an issue where this is clarified by the VS Code team:

* https://github.com/microsoft/vscode/issues/157630

**To Reproduce**

1. Open a Clojure file in Calva
2. Confirm that the Outline navigation works
3. Add a line
4. The Outline now navigates to lines offset by -1 for symbols after where you added the line.

What's a bit extra strange here is that if I undo the change of adding a line, the Outline now links to incorrect line offset by +1.
 
**Expected behavior**

The outline should navigate to the new line locations of the symbols is lists as the file is edited.

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
Sure, I can add this, but in a bit of a hurry here. Please let me know if it would help with a log.
</pre>
</details>

<details>
 <summary><b>Log - clojure-lsp</b></summary>
<pre>
Same.
</pre>
</details>

**User details (please complete the following information):**
 - OS: [e.g. ArchLinux, MacOS, Windows 10]
 - Editor [e.g. emacs, nvim, VSCode (Calva)]
 - Version: (post the result of `clojure-lsp --version`)

**Additional context**

**Comment by PEZ** [comment]
Related to this is that sticky scrolling in VS Code would get much better if the Outline would have some more depth. Currently it seems to only include top level symbols?

**Comment by mainej** [comment]
clojure-lsp bases its documentSymbol data on the file's analysis. But, at the moment it doesn't wait for any currently running analysis to finish before replying to a documentSymbol request. My guess is that Calva sends didChange, which starts an (asynchronous) analysis, and then immediately documentSymbol. The second request uses the analysis that already exists, which, assuming the analysis hasn't finished, is for the _prior_ version of the file. That's why the first edit is off by -1 and undoing is off by +1. In each case, clojure-lsp is providing documentSymbol data for how the file was a moment ago.

If I'm right, that's a really quick fix. I'll see if I can reproduce the problem and whether I can fix it.

**Comment by mainej** [comment]
@PEZ I believe https://github.com/clojure-lsp/clojure-lsp/pull/1180 will fix this.

**Comment by ericdallo** [comment]
Looks good and makes sense @mainej, @PEZ would you mind test with that PR's clojure-lsp?

**Comment by aiday-mar** [comment]
Hi I link hereby the relevant sticky scroll issue : https://github.com/microsoft/vscode/issues/157630
