### ISSUE TITLE
Add missing requires from `comment` should not add to ns

### ISSUE THREAD

**Issue by mainej** [clojure-lsp/clojure-lsp#1316]
**Is your feature request related to a problem? Please describe.**

Currently `add-missing-require` always adds the missing namespace to the `ns`'s `:require` form. But when in an RCF, a top-level `(comment ...)` form, this isn't what some users want. They feel that this clutters their `ns` with namespaces that aren't really used. They'd prefer that the missing namespace be put in a `(require ...)` form in the RCF.

**Describe the solution you'd like**

I'd like one of two things. I think the best would be a configuration option that modified `add-missing-require`'s behavior. Bonus points for adding the missing namespace to an existing `(require ...)`. Alternatively, there could be a new command.

**Describe alternatives you've considered**
It's possible to add `(require ...)` by hand.

**Additional context**
See discussion in [Slack](https://clojurians.slack.com/archives/CPABC1H61/p1664877429715259)

**Comment by ericdallo** [comment]
I see 2 good possible options:
- Add support as a flag, we can discuss the default value.
- Always ask when adding a require inside a RCF if user wants to add on comment or top-level ns

**Comment by mainej** [comment]
Yeah, either of those would work. Prompting the user is a nice idea. This is a rare enough use-case that a prompt wouldn't be too intrusive, IMO.

**Comment by blnote** [comment]
Hi, I'm working on this a little: right now I've introduced a flag `add-require-inside-comments` and  I'm showing a prompt whenever the code-action `add-missing-libspec` is called within a comment form and this flag is not set (neither true or false). 
However, `code-completion` adds lib-specs too and asking might be difficult in this case, since the edit seems to be done before the user commits to a completion (?)...
so maybe I'd just stick to the setting of the flag in this case and default to the old behavior if it is not present ? ...just writing down thoughts :)

**Comment by ericdallo** [comment]
Fixed by #1767
