### ISSUE TITLE
`:style/indent` support for cljfmt format

### ISSUE THREAD

**Issue by vemv** [clojure-lsp/clojure-lsp#1420]
## Context

CIDER has the notion of `:style/indent`: https://docs.cider.mx/cider/indent_spec.html

This format follows clojure-mode conventions. However this format, for the vast majority of real-world usages, is a single digit e.g. `:style/indent 3` and therefore it's trivially translatable to cljfmt's format.

## Problem statement

clojure-lsp's cljfmt integration is currently unaware of :style/indent. This causes inconsistent indentation for users of different tooling.

## Proposed solution

Use clj-kondo analysis to determine macros' metadata. Translate it and use it.

I'd assume that this analysis data is already cached. Perhaps a cljfmt-specific cached bit could be established.

Lastly, I'd note that defmacros change rarely, so issues like cache staleness, or analysis performance would likely be very relative.

LMK what you think!

Cheers - V

**Comment by ericdallo** [comment]
@vemv currently clojure-lsp just passes the whole string to cljfmt [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/lib/src/clojure_lsp/feature/format.clj#L46), how that would work exactly? Would we need to parse the code and check the metadata of all functions calls and somehow convert to a cljfmt setting, is that your idea?

**Comment by ericdallo** [comment]
Got it, what I mean with function calls is for the code:
```clojure
(ns a)
(defmacro bar [& body] ...)

(ns b)
(defn foo []
  (bar 1 2 3))
```
when formatting the b ns, we'd need to check all call usages (`defn`, `bar` etc) to see if they are a macro call and if they are, retrieve the metadata if any, then convert to a cljfmt config for that macro, does that makes sense?

if so, I think we could try to do a POC and check how that affect performance, because we would now have this flow:

1. receives the string from LSP request
2. (NEW) get all kondo `var-usages` analysis of this ns
3. (NEW) map macro `var-usages` metadata doing something similar to that code snippet you linked
3. passes the string to cljfmt along with the additional config

**Comment by ericdallo** [comment]
I think we are agreeing here but maybe I'm not making clear what clojure-lsp would need to do.
From cljfmt side, It just need something like:
```clojure
{:indents {bar [[:block 1]]}}
```
Right?

The issue is we would need to get the metadata from the macro definition and convert to that setting when formatting.

The main problem for clojure-lsp is that we only have the string of the code, but we could have in the in-memory atom all the macros that have that style metadata and when formatting just adapt the style to the cljfmt setting `[[:block ...]]`.

If that doesn't make sense, maybe I misunderstood the issue

**Comment by ericdallo** [comment]
Yes, we do have that in db analysis, I thought we would need to parse the code being formatted but we can rely on kondo analysis since the metadata is really on the var-definition, so I think it's easier, we still need to cache that to avoid spending too much time on `formatting` getting all macros metadata and adapting to cljfmt config but sounds viable :)
