### ISSUE TITLE
Restart action on classpath fail message doesn't work

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#1500]
It seems that this [window/ShowMessageRequest](https://github.com/clojure-lsp/clojure-lsp/blob/c04df1c50afa5738e3e84f6367b1875ad84c3c8b/lib/src/clojure_lsp/classpath.clj#L131) is not working properly, the value is never returned until the `::timeout`, I did some debugging and testing with the reply the code works perfectly, so maybe it's related with that not working only during initialize?
Happens with Emacs/lsp-mode and VScode/Calva, so seems a server bug indeed.

**Comment by ericdallo** [comment]
Any thoughts @mainej ?

**Comment by mainej** [comment]
Yes, I can explain why this happens. We've been struggling with something somewhat similar at Scarlet too.

* In a thread, lsp4clj [reads](https://github.com/clojure-lsp/lsp4clj/blob/92665ae23e99ee9ca4d9e3ccf0063f6d74885540/src/lsp4clj/io_chan.clj#L103) messages from the client and adds them to the `input-ch`, a `(chan 1)`.
* In a [loop](https://github.com/clojure-lsp/lsp4clj/blob/master/src/lsp4clj/server.clj#L206-L209) it takes a message off the `input-ch`, then forwards the message on to clojure-lsp.
* In the case of startup, this message is the `initialize` request. clojure-lsp processes most requests [asynchronously](https://github.com/clojure-lsp/clojure-lsp/blob/master/cli/src/clojure_lsp/server.clj#L28-L29), which means the lsp4clj loop can recur to read the next message. But `initialize` is different; it is processed synchronously, so that we can be sure it finishes before we start receiving other requests. This means that the lsp4clj loop doesn't recur until clojure-lsp has finished processing `initialize`.
* In the case of this bug, in the middle of processing `initialize`, clojure-lsp sends a `window/showMessageRequest` to the client. The client receives the request and responds.
* But because the lsp4clj loop doesn't recur, the client's response isn't passed to clojure-lsp.
* So, clojure-lsp is waiting for a client response from lsp4clj, and lsp4clj is waiting for clojure-lsp to finish `initialize`. This is a deadlock.
* Eventually we escape the deadlock because of the timeout, but the restart feature is broken.

At Scarlet, we're facing a related problem.
* Occasionally in the Scarlet language server, in the middle of receiving a **notification** we send a request. The client receives the request and responds.
* But, because all inbound notifications are synchronous in lsp4clj (to ensure that `didChange` notifications are processed in order) reads off the `input-ch` are blocked. The Scarlet server never receives the response, even though the client has sent it. The client response can't get through until the server is finished with the notification, and the server can't finish the notification until it receives the client response. Again, deadlock.

I had one idea of how to fix this—in lsp4clj we could separate inbound (and probably outbound) messages into two streams, those initiated by the client and those initiated by the server. That way the server would be able to continue receiving responses on the server-initiated stream, even while it was blocking the client-initiated stream. I haven't thought about how to do this, or even whether it's the _right_ way to fix it, so feedback welcome.

**Comment by ericdallo** [comment]
Oh, it makes sense now, and your suggestion looks pretty good to me, I don't think we would face more deadlocks if using that approach and if we face would be a pretty complex corner case or a future problem 😅
