### ISSUE TITLE
lsp client gets "Error: Header must provide a Content-Length property"

### ISSUE THREAD

**Issue by FongHou** [clojure-lsp/clojure-lsp#283]
With latest build, clojure-lsp initialization gets "uncaughtException Error: Header must provide a Content-Length property.", and it seems never finishing. Almost all lsp features stop working.

A google search shows lots of other lsp implemenations had the same issue. Looks like Content-Length header is required according to https://microsoft.github.io/language-server-protocol/specification

**Comment by snoe** [comment]
I was running into this in dev, it was due to my dev version of kondo printing to stdout. Not sure if this helps but any sort of println/prn logging should be suspect.

**Comment by ericdallo** [comment]
Hum, good guess @snoe, @borkdude, this started to happen with some recent clj-kondo bump, do you know if clj-kondo is printing anything to console like debug prints?

**Comment by ericdallo** [comment]
BTW, I can't reproduce it with Emacs lsp-mode

**Comment by snoe** [comment]
I think we can `run!` wrapped in `with-out-str` https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/crawler.clj#L114 if we suspect that's the case (and to be clear I'm not saying this instance is clj-kondo, just that I was doing dev work and caused this to happen to myself)

**Comment by ericdallo** [comment]
I see, I think we can wrap it with with-out-str for safety

**Comment by dharrigan** [comment]
Hi,

I'm able to reproduce this 100% of the time like this (I'm using neovim + coc + clojure-lsp)

* Ensure there is no `.lsp` directory in your project directory
* Open up a `deps.edn` file (for example)
* It will spin saying `initializing languageserver.clojure-lsp`
* After a short while the error will appear `"Uncaught Exception: Header must provide a Content-Length property."`
* Exit vim
* Re-open the same `deps.edn` file and all will be well (clojure-lsp will launch etc...without error)
  * (because the `.lsp` directory now exists)
* Exit vim
* Delete the `.lsp` directory
* Open up the `deps.edn` file...and error occurs once again.

**Comment by ericdallo** [comment]
@dharrigan is it possible to get the stdout from clojure-lsp process?

**Comment by ericdallo** [comment]
Found the issue, I fixed it and make it sure doesn't have next time :)
Thanks for the report!
