### ISSUE TITLE
clojure-lsp highlighting unresolved vars where clj-kondo output shows no such issue

### ISSUE THREAD

**Issue by devn** [clojure-lsp/clojure-lsp#352]
**Describe the bug**
`clojure-lsp 2021.02.24-14.23.08` is highlighting unresolved vars where clj-kondo (`clj-kondo v2021.02.28`) does not. I did not construct the smallest reproducible case, but I can confirm after removing .clj-kondo/.cache and .lsp/sqlite* that the output of clj-kondo --lint src does not show this to be unresolved in its output, but clojure-lsp highlights it as unresolved.

**Steps to reproduce:**
1. `git clone https://github.com/devn/lsp-repro`
2. Note the presence of `.clj-kondo/config.edn` in the root.
2. Open src/lsp_repro/core.clj and watch it highlight the http-kit/get as an unresolved var
3. Run `clj-kondo --lint src` and see it produces no such warning
4. Quit emacs
5. Clear the caches and LSP database `rm -rf .clj-kondo/.cache && rm .lsp/sqlite.db`
6. Reopen emacs
7. See that the problem persists
8. Now remove the clj-kondo config.edn from the equation: `mv .clj-kondo{,.bak}`
9. Reopen emacs and see the problem is gone.
10. Bring it back: problem returns.

**Expected behavior**
clojure-lsp should not highlight an unresolved var when it is resolvable.

**Screenshots**
![Screen Shot 2021-03-01 at 6 35 29 PM](https://user-images.githubusercontent.com/10421/109578530-f4892100-7abc-11eb-8cf7-0a3e75d16cb5.png)

**User details (please complete the following information):**
 - OS: MacOS
 - Editor emacs
 - Version: `clojure-lsp 2021.02.24-14.23.08`

**Additional notes:**
I saw this problem both before and after upgrading clj-kondo. In both cases, I cleared .clj-kondo/.cache and .lsp/sqlite*.

```
==> Upgrading 1 outdated package:
borkdude/brew/clj-kondo 2020.09.09 -> 2021.02.28
```

**Comment by ericdallo** [comment]
Thank you for the detailed report, it helps a lot.
The issue here is with clj-kondo cache. When clojure-lsp start, it call clj-kondo to scan the whole classpath, clj-kondo then creates caches for each file scanned, your issue happens if after the classpath is cached, when you lint a single file it'll then report the unresolved symbol.

We can confirm that it's a clj-kondo issue with two commands:

Lint the whole classpath first to create the `.clj-kondo/.cache`:
```bash
$ clj -Sdeps '{:deps {clj-kondo {:mvn/version "2021.03.01-20210228.215804-2"}}}' -m clj-kondo.main  --lint $(lein classpath)
```

Then if you lint a single file (when emacs open the file or change the content):
```bash
$ clj -Sdeps '{:deps {clj-kondo {:mvn/version "2021.03.01-20210228.215804-2"}}}' -m clj-kondo.main  --lint src/lsp_repro/core.clj
=> src/lsp_repro/core.clj:7:5: warning: Unresolved var: http/get  
```

You can see clj-kondo warns about that unresolved var, if you delete manually the cache of that file with:
```bash
rm .clj-kondo/.cache/2021.03.01-SNAPSHOT/clj/org.httpkit.client.transit.json
```

You will see that now clj-kondo scan resolve the symbol:
```bash
$ clj -Sdeps '{:deps {clj-kondo {:mvn/version "2021.03.01-20210228.215804-2"}}}' -m clj-kondo.main  --lint src/lsp_repro/core.clj
```

So the issue is that for some reason clj-kondo is not recognizing that when run a full lint, WDYT @borkdude?

**Comment by borkdude** [comment]
The issue is simply that `http/get` gets defined using a macro:

https://github.com/http-kit/http-kit/blob/d12b1667a62785c5bcc635462958a5f85f7db303/src/org/httpkit/client.clj#L307

Adding a config for that macro will resolve the issue `{:lint-as {org.httpkit.client/defreq clojure.core/def}}`.

**Comment by ericdallo** [comment]
Oh got it, and when clj-kondo lint a single file without context of the whole classpath, it doesn't warn about the macro, right?
I confirmed the issue is fixed using the `:lint-as` above, I'll add more details to the `lint` section of clojure-lsp.

Thanks for the help @borkdude

**Comment by devn** [comment]
Huh, my apologies! I don't remember this highlighting as unresolved in previous versions. Though perhaps I am mistaken.
