### ISSUE TITLE
Not finding documentation using textDocument/hover

### ISSUE THREAD

**Issue by tuh8888** [clojure-lsp/clojure-lsp#477]
**Describe the bug**
In Emacs, using `lsp-describe-thing-at-point` on a clojure fn, such as `map` or `filter` returns markdown only containing the source location and the function name.

**To Reproduce**
1. Open clojure file
2. Navigate to a symbol representing a function such as `map`.
3. Type `M-x lsp-describe-thing-at-point` 
4. A help buffer pops with the minimal info described above.

**Expected behavior**
The help buffer should show the doc-string of the function under the point.

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 08:56:02 PM] Sending request 'textDocument/hover - (85)'.
Params: {
  "textDocument": {
    "uri": "file:///home/harrison/.local/share/chezmoi/bin/executable_theme-toggle.clj"
  },
  "position": {
    "line": 5,
    "character": 3
  }
}

[Trace - 08:56:02 PM] Received response 'textDocument/hover - (85)' in 2ms.
Result: {
  "contents": {
    "kind": "markdown",
    "value": "```clojure\nmap\n```\n----\n*[/home/harrison/.local/share/chezmoi/bin/executable_theme-toggle.clj](file:///home/harrison/.local/share/chezmoi/bin/executable_theme-toggle.clj)*"
  },
  "range": {
    "start": {
      "line": 5,
      "character": 1
    },
    "end": {
      "line": 5,
      "character": 4
    }
  }
}

</pre>
</details>

**User details (please complete the following information):**
 - OS: ArchLinux
 - Editor: emacs
 - Version: clojure-lsp 2021.07.12-12.30.59
clj-kondo 2021.06.18

**Comment by ericdallo** [comment]
I can't repro the issue: 
![image](https://user-images.githubusercontent.com/7820865/125453431-1a1fcddc-2daa-4763-8e00-91596300d6fd.png)

@tuh8888, this usually happens when server didn't scan the project properly. 
1. make sure you have the project root configured properly, check it with `lsp-workspace-folders-remove` and then `lsp` again.
2. make sure servers analyze the classpath properly, check the [server log](https://clojure-lsp.github.io/clojure-lsp/troubleshooting/#getting-server-log) to confirm that.
