### ISSUE TITLE
List implementations of protocol fns

### ISSUE THREAD

**Issue by slipset** [clojure-lsp/clojure-lsp#656]
When coding polymorphically, say with 
```clj
(defprotocol IFoo
   (foo [bar])) 

;; some other part of the code

(foo bar)
```
Today, when clicking on "go to definition" of the `(foo bar)` you jump to the protocol definition. It would be very useful to get a list of all known concrete implementations of `foo` 

The same applies for multimethods`.

**Comment by ericdallo** [comment]
@slipset could you elaborate the use case please?
ATM if you find all the reference of `foo` both from the usage or the protocol definition, it should find all foo calls

**Comment by slipset** [comment]
Ah, I guess what I'm after is in

```clj
;;  ns
(foo bar) ;; click "Go to definition"
```
Here "Go to definition gets me to the protocol definition. I want to be presented with all the possible implementations of the protocol. Find references show me all usages, but not (only) the possible implementations.

Somewhat like what is described [here](https://www.jetbrains.com/help/rider/Navigation_and_Search__Go_to_Implementation.html) (for Intellij)

**Comment by ericdallo** [comment]
I see, what you seek is the LSP method ]textDocument/implementation](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_implementation), I'll check what would be needed to implement that

**Comment by ericdallo** [comment]
I opened a clj-kondo issue as we indeed would need information about the defrecord methods to implement that

**Comment by lyderichti59** [comment]
These two features would be super neat to have ! I would love to use them (both defrecord implementations and multi-method implementations)

I wonder to what extent we could have some type inference ?

Let say I have 
```clojure
(defprotocal MyProtocol
  (method [_]))
  
(defrecord ImplA [arg]
  (method [_] (println arg)))
 
 (defrecord ImplB [arg]
  (method [_] (prn arg)))
  
  (let [client (->ImplB "hello")]
    (method client))
  ```
  
If we can somehow guess that `client` is an instance of `ImplB`, then when we'll have the `textDocument/implementation` list, we will be able to pick the most relevant implementation directly instead of selecting the right one from a list.


Same thing applies to `(defmethod method :dispatch-value ...)`
If we can guess the dispatch value (there are quite obvious edge cases for example when the dispatch function is just navigating in a data structure (map or vector for example)), then we'll be able to find the most relevant implementation of multimethod depending on the call site..

**Comment by ericdallo** [comment]
@lyderichti59  Unfortunately, that's not that easy as it's almost a runtime analysis thing, we would need to make too many changes on kondo side or some ad-hoc thing to implement that :/

**Comment by ericdallo** [comment]
I'm making this issue only related to defprotocol/defrecord/deftype and creating a new one for multimethods

**Comment by ericdallo** [comment]
Done on https://github.com/clojure-lsp/clojure-lsp/commit/a13d2071184b0aa6e665215f4abc1f90e55fac4d

**Comment by ericdallo** [comment]
#751 was merged, now we have both find implementations for defmulti and defprotocols 🎉
