### ISSUE TITLE
Exception on move coll code actions

### ISSUE THREAD

**Issue by ericdallo** [clojure-lsp/clojure-lsp#803]
![image (5)](https://user-images.githubusercontent.com/7820865/156903627-7399c2b6-b21c-4d95-bb49-412ae6a23b27.png)

cursor was on https://github.com/clj-kondo/clj-kondo/blob/master/src/clj_kondo/impl/utils.clj#L17 col 9

**Comment by mainej** [comment]
I can't trigger this NPE from the code you flagged @ericdallo ... but I _can_ trigger an NPE with the same stack trace from a whitespace/comment line in an otherwise-empty file. You said something about being in the middle of checking out a branch. Could something weird have happened with the state of this file?

In any case, the NPE I can reproduce should be fixed, hopefully fixing the error you saw at the same time. There are two ways to do that... I could make top-level movement a no-op (and exclude it from the actions menu). Or I could teach move-coll-entry to move top-level forms, sort of like a smarter `sp-transpose-sexp`.

I'd like to do the second, but my attempt caused very strange behavior. The top-level forms got moved, but they also got duplicated for some reason. (When they get duplicated many times the file size gets huge, and clojure-lsp gets very slow, spending many minutes using 100% of at least one core. That's interesting in itself, but can be explored separately.) So, I'm going to make top-level movement a no-op for now, with plans to submit a PR for moving top-level nodes later.
